### ISSUE TITLE
Unable to create filesystem if directory is link

### ISSUE THREAD

**Issue by valksen** [althonos/fs.sshfs#41] opened 2020-10-08 17:13 UTC
If I try to open
    "sftp:://<user>@<server>/home/"
it works fine;
but
    "sftp:://<user>@<server>/bin/"
is not working because  'bin' is a link to '/usr/bin/'

In old implementation of fs ( pyrhonV3.4 ) iboth cases works fine
-Valeri

**Comment by althonos** [comment] 2021-01-08 17:12
Hi @valksen ,

this is a bug caused by a change in how Pyfilesystem works with symlinks. This caused the `SSHFS` implementation to divert from the expected behaviour; I have written a patch and will push a new release ASAP.

**Comment by althonos** [comment] 2021-01-08 17:58
This should be fixed in `v0.13.0` (I have added a regression test to the test suite as well).

**Closed as completed by althonos** 2021-01-08 17:58 UTC
Labels: bug, fixed
